spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cuenta_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: false
server:
  port: 8082
